apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-cep
  description: API simples em FastAPI para consultar CEP via ViaCEP
  tags:
    - api
    - rest
    - python
    - fastapi
    - docker
    - backend
    - experimental

  annotations:
    github.com/project-slug: rafael-buttignon/platform-gitops-brw
    backstage.io/techdocs-ref: dir:.

  links:
    - url: https://github.com/rafael-buttignon/platform-gitops-brw/tree/main/api/cep
      title: Repositorio (GitHub)
      icon: github
    - url: http://localhost:8081/docs
      title: Swagger UI (FastAPI)
      icon: docs
    - url: http://viacep.com.br
      title: ViaCEP
      icon: web
      type: external-dependency
spec:
  type: service
  lifecycle: experimental
  owner: group:default/team-cep
  providesApis:
    - api:default/api-cep
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-cep
  description: API de consulta de CEP com validacao e integracao ao ViaCEP
spec:
  type: openapi
  lifecycle: experimental
  owner: group:default/team-cep
  definition: |
    openapi: 3.0.3
    info:
      title: API CEP
      version: 1.0.0
      description: API para consulta de CEPs brasileiros usando ViaCEP.
    servers:
      - url: http://localhost:8081
        description: Ambiente local (Docker)
    tags:
      - name: status
        description: Endpoints de status e healthcheck
      - name: cep
        description: Consulta de CEP
    paths:
      /:
        get:
          tags: [status]
          summary: Status basico do servico
          operationId: getRoot
          responses:
            '200':
              description: Servico ativo
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/RootResponse'
      /health:
        get:
          tags: [status]
          summary: Healthcheck da API
          operationId: getHealth
          responses:
            '200':
              description: API saudavel
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/HealthResponse'
      /cep/{cep}:
        get:
          tags: [cep]
          summary: Consulta dados de um CEP
          operationId: getCep
          description: |
            Aceita CEP com 8 digitos, com ou sem hifen.
            Exemplo valido: 01001000 ou 01001-000.
          parameters:
            - in: path
              name: cep
              required: true
              description: CEP brasileiro com 8 digitos (com ou sem hifen)
              schema:
                type: string
                example: '01001000'
          responses:
            '200':
              description: CEP encontrado
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ViaCepResponse'
            '400':
              description: CEP invalido
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
                  example:
                    detail: CEP invalido
            '404':
              description: CEP nao encontrado
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
                  example:
                    detail: CEP nao encontrado
            '502':
              description: Falha de rede/servico ao consultar ViaCEP
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
            '504':
              description: Timeout ao consultar ViaCEP
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ErrorResponse'
    components:
      schemas:
        RootResponse:
          type: object
          required: [service, status]
          properties:
            service:
              type: string
              example: api-cep
            status:
              type: string
              example: ok
        HealthResponse:
          type: object
          required: [status]
          properties:
            status:
              type: string
              example: healthy
        ErrorResponse:
          type: object
          required: [detail]
          properties:
            detail:
              type: string
              example: CEP invalido
        ViaCepResponse:
          type: object
          description: Resposta retornada pelo servico ViaCEP
          properties:
            cep:
              type: string
              example: 01001-000
            logradouro:
              type: string
              example: Praca da Se
            complemento:
              type: string
              example: lado impar
            unidade:
              type: string
              example: ""
            bairro:
              type: string
              example: Se
            localidade:
              type: string
              example: Sao Paulo
            uf:
              type: string
              example: SP
            estado:
              type: string
              example: Sao Paulo
            regiao:
              type: string
              example: Sudeste
            ibge:
              type: string
              example: "3550308"
            gia:
              type: string
              example: "1004"
            ddd:
              type: string
              example: "11"
            siafi:
              type: string
              example: "7107"
