apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devops-portal
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: rafael-buttignon/platform-gitops-brw
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
